name: BewerbungsPluginJannick
version: ${project.version}
main: de.ruben.bewerbungsplugin.Bewerbungsplugin
api-version: 1.16
authors: [ AldiChef ]
description: Application plugin for the Menia.net network
